sds-2021-summer-algorithm/java

solution/BOJ_20055_컨베이어-벨트-위의-로봇/황정훈.java
전에 파이썬으로 풀었던 문제긴한데..
시간, 공간적으로 자바가 훨씬 좋긴하네요
=> [황정훈] 컨베이어벨트 위의 로봇

solution/BOJ_20055_컨베이어_벨트_위의_로봇/yess.java
저도 메모리사용량 23196KB, 시간 444ms 이나 걸리네요... ! 
금요일까지 고민 더 해볼게요 ! ㅎ
=> [양은서] 컨베이어 벨트위의 로봇

solution/BOJ_21608_상어초등학교/황정훈.java
전에 풀었던 문제긴한데...
로직자체에 큰 변화는 없는데 pypy도 아니고 python 보다도 느리게나오네요..?
갓이썬,,
=> [황정훈] 상어초등학교

solution/BOJ_21608_상어초등학교/ykm
제 코드는 O(16N^2)인것 같은데 제출현황보니까 코드는 못보게 되어 있었지만 c++에 8ms인게 있더라구요... 도대체 어떻게 한건지 궁금..
=> [유경민] 상어초등학교

solution/BOJ_15684_사다리-조작/황정훈.java
나름대로 불필요한 연산없이 풀었다고 생각했는데.. 맞은사람들 런타임을 보니 정말 숨이 턱 막히네요ㅠㅠ
=> [황정훈] 사다리조작

solution/BOJ_15684_사다리-조작/ykm
x,y를 반대로 입력받은걸 모르고 한참 고민했습니다...
=> [유경민] 사다리 조작

solution/BOJ_16234_인구-이동/황정훈.java
상어중학교 문제와 상당히 비슷해서 해결하는데는 크게 무리없었지만
런타임이 다른사람들에 비해 썩 좋지못한거 같아서 조금 더 개선할 필요가 있어보입니다..ㅠ
=> [황정훈] 인구이동

solution/BOJ_15684_사다리-조작/백인찬.java
main 메소드가 아닌 다른 메소드 내에서 exit하는 방법을 java에서는 어떻게 하는지 몰랐는데, 이 기회에 알게 되었다.
또 System의 IO를 쓸 것인지 Buffered IO를 쓸 것인지 정하고 통일성 있게 코드를 작성하는게 깔끔해 보일 것 같다.
=> [백인찬] 사다리조작

solution/BOJ_11438_LCA2/황정훈.java
=> [황정훈] lca2

solution/BOJ_11438_LCA2/ykm.java
=> [유경민] LCA2

solution/BOJ_11438_LCA2/백인찬.java
LCA를 찾을 때 Bottom-up 방식으로 하다보면 중간에 건너뛰는 LCA가 있을 수 있어서 Top-down 방식으로 하는 것에 유의해야 합니다
=> [백인찬] LCA2

solution/BOJ_11438_LCA2/김지원.java
=> [김지원] 11438_LCA2 (성공)

solution/BOJ_18428_감시-피하기/백인찬.java
변수 선언 위치 때문에 3번이나 맞왜틀을 시전했네요 ㅠㅠ
=> [백인찬] 감시 피하기

solution/BOJ_18428_감시-피하기/김지원.java
=> [김지원] 18428_감시피하기 (O)

solution/BOJ_1963_소수-경로/백인찬.java
이전에 한번 풀었던 문제이지만 bfs가 활용도가 매우 높다는 걸 알 수 있는 문제였습니다. 런타임을 더 줄일 수 있는 방법이 안 떠오르네요
=> [백인찬] 소수경로

solution/BOJ_1339_단어-수학/백인찬.java
이전에 풀었던 문제라 이번에는 런타임 줄이는데 집중해봤습니다. 이전에는 Map으로 풀었었는데 오히려 배열로 푸는게 간단하네요
아래는 예전에 풀었던 풀이와 런타임입니다.
왜 long으로 했는지는 모르겠네요,, 그때의 나...
```Java
import java.io.*;
import java.util.*;
public class Main {
static Map<Character, Long> map = new HashMap<>();
static String[] words;
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));
StringBuilder sb = new StringBuilder();
int N = Integer.parseInt(br.readLine());
words = new String[N];
for (int i = 0; i < N; i++) {
words[i] = br.readLine();
}
for (int i = 0; i < N; i++) {
int len = words[i].length();
for (int j = 0; j < len; j++) {
long coef = (long) Math.pow(10, len - (j+1));
char c = …
```
=> [백인찬] 단어 수학

solution/BOJ_1339_단어-수학/ykm.java
왜 제가 고민해서 추가한 부분은 안되고 무지성 완전 탐색은 통과 한건지...
=> [유경민] 단어수학

solution/BOJ_1963_소수-경로/ykm.java
큐 초기화 안한걸 모르고... 논리 오류진지 한참 고민했네요..
10번 넘게 틀렸는데!!
=> [유경민] 소수 경로

solution/BOJ_1931_회의실배정/백인찬.java
예전에 C++로 푼 적이 있는데 C++이 말도 안되게 빠르긴 하네요
=> [백인찬] 회의실 배정

solution/BOJ_10844_쉬운-계단-수/백인찬.java
=> [백인찬] 쉬운 계단수

solution/BOJ_10844_쉬운-계단-수/ykm.java
dp 아이디어를 떠올리는게 어려워요ㅠㅠ
앞선 분들이 long언급하신덕에 왜맞틀시간이 짧았습니다.
=> [유경민] 쉬운계단수

solution/BOJ_1931_회의실배정/ykm(success).java
=> [유경민] 회의실 배정

solution/BOJ_17141_연구소-2/백인찬.java
예전에 풀었던 문젠데 런타임이 조금 나아져서 다행이네요
=> [백인찬] 연구소2

solution/BOJ_17141_연구소-2/ykm.java
=> [유경민] 연구소2 (성공)

solution/BOJ_17141_연구소-2/김지원.java
=> [김지원] 연구소 2 (O)

solution/BOJ_10844_쉬운-계단-수/황정훈.java
=> [황정훈] 쉬운계단수

solution/BOJ_1931_회의실배정/황정훈.java
종료시간이 같은경우를 생각못하고 한참 맞왜틀 시전..ㅠㅠ
=> [황정훈] 회의실배정

solution/BOJ_3665_최종순위/ykm.java
=> [유경민] 최종순위

solution/BOJ_2636_치즈/김지원.java
=> [김지원] 치즈 (O)

solution/BOJ_17142_연구소-3/황정훈.java
=> [황정훈] 연구소3

solution/BOJ_17142_연구소-3/ykm.java
=> [유경민] 연구소3 (성공)

solution/BOJ_16235_나무-재테크/황정훈.java
런타임은 그렇게 좋지못하지만 그래도 직관적으로 구현하려고 많이 노력했네요.
=> [황정훈] 나무재테크

solution/BOJ_17141_연구소-2/황정훈.java
=> [황정훈] 연구소2

solution/BOJ_3665_최종순위/황정훈.java
푸는데 5시간걸렸어요.. 다른분들 풀이를 듣고나서 푼건데도 진짜 너무어려웠네요ㅠㅠㅠ
=> [황정훈] 최종순위

solution/BOJ_17406_배열돌리기/김지원.java
=> [김지원] 배열돌리기 4 (O)

solution/BOJ_1167_트리의-지름/ykm.java
시간초과와... 메모리 초과... 모두 겪고 결국 마지막에는 지원님 코드를 참고 했습니다ㅠㅠ
=> [유경민] 트리의 지름 (통과)

solution/BOJ_1167_트리의-지름/김지원.java
=> [김지원] 트리의 지름 (O)

solution/BOJ_2075_N번째-큰수/ykm.java
=> [유경민] N번째 큰수

solution/BOJ_2075_N번째-큰수/김지원.java
=> [김지원] N번째 큰수

solution/BOJ_2075_N번째-큰수/황정훈.java
=> [황정훈] N번째큰수

solution/BOJ_17406_배열돌리기/황정훈.java
=> [황정훈] 배열돌리기4
